### ISSUE TITLE
Missing Purpose String in Info.plist

### ISSUE THREAD

**Issue by hardikamal** [hyperoslo/Gallery#154]
Hi,
When submitted my app I received an email as below. But I am not using Location anywhere in my app. I have found location related code in this library. How can I solve this?

Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationWhenInUseUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).

**Comment by Schaefers** [comment]
Did you click on the link attached?

https://developer.apple.com/documentation/uikit/protecting_the_user_s_privacy/accessing_protected_resources

**Comment by lawmaestro** [comment]
I'm not sure why this issue was closed as the only possible workaround has issues and isn't currently documented. If:

a) We don't require location information then we shouldn't have to provide a `NSLocationWhenInUseUsageDescription` string.
b) We do require location information then declaration of a `NSLocationWhenInUseUsageDescription` should be documented.

I've addressed this issue with the following [PR](https://github.com/hyperoslo/Gallery/pull/188). This is turn resolves the App Store submission warnings about not providing a purpose string
