### ISSUE TITLE
Lightbox Preview problem

### ISSUE THREAD

**Issue by jackpaster** [hyperoslo/Gallery#9]
@zenangst @fespinoza @nashby @timkurvers @sindrenm First of all this project is amazing, but I have a problem. once ive taken the images i want to preview them in this custom view controller i made with a scroll view inside of it. The lightbox solution you have for presenting your images and videos is nice but do you have something custom like a lightbox scroll view instead of a lightbox view controller that I can call in my main.storyboard so I can have additional elements in my view controller alongside the lightbox scroll view. 

Skype: Jackpaster22

**Comment by onmyway133** [comment]
@jackpaster Hi, `Lightbox` is designed as a separated module and accessible via ViewController, so that it is easy to use. The inside `scrollView` is not `public` https://github.com/hyperoslo/Lightbox/blob/master/Source/LightboxController.swift#L23, but you can fork and make it custom the way you need it. Hope it help
